---
# Cannot get this to work for some reason
#AWSTemplateFormatVersion: AWSTemplateFormatVersion: '2010-09-09'

Description: This template creates a new Elastic Load Balancer (ELB) into an existing VPC.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

# These show up in the console and are expected to be provided by the operator
Parameters:
    Name:
        Description: 'A friendly name or description of the web ACL'
        Type: 'String'
        Default: 'Silly Example'

    MetricName:
        Description: 'A friendly name or description for the Amazon CloudWatch metric of this web ACL.'
        Type: 'String'
        Default: 'SillyExample'

    Priority:
        Description: 'The order in which AWS WAF evaluates the rules in a web ACL. AWS WAF evaluates rules with a lower value before rules with a higher value.'
        Type: 'Number'
        Default: 1

Resources:
    InterestingAddresses:
        Type: 'AWS::WAF::IPSet'
        Properties:
            IPSetDescriptors:
                -
                    Type: IPV4
                    Value: '64.222.174.146/32'
            Name: 'List of ip addresses we want to monitor'

    SpecificAddressRule:
        Type: 'AWS::WAF::Rule'
        Properties:
            MetricName: 'SpecificAddressMetric'
            Name: 'Matches against a specific ip address'
            Predicates:
                -
                    DataId:
                        Ref: InterestingAddresses
                    Negated: false
                    Type: IPMatch
    ACL:
        Type: 'AWS::WAF::WebACL'
        Properties:
            DefaultAction:
                Type: ALLOW
            MetricName:
                Ref: MetricName
            Name:
                Ref: Name
            Rules:
                -
                    Action:
                        Type: COUNT
                    Priority:
                        Ref: Priority
                    RuleId:
                        Ref: SpecificAddressRule

Outputs:
    ACL:
        Description: A reference to the Web Application Firewall ACL
        Value:
            Ref: ACL
